CREATE OR REPLACE TRIGGER T_B_I_CRENEAU_CHEV 
BEFORE INSERT OR UPDATE 
ON CRENEAU
FOR EACH ROW 
DECLARE 
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM CRENEAU
    WHERE GRPC = :NEW.GRPC
    AND JOURC = :NEW.JOURC
    AND EST_CRENEAU_DISJOINT(:NEW.HEUREDC, :NEW.HEUREFC, HEUREDC, HEUREFC) = 'FALSE';
    
    IF(v_count > 0)
    THEN
        RAISE_APPLICATION_ERROR(-20006, 'Un groupe ne peut pas avoir deux enseignements en même temp');
    END IF;
END;
/