CREATE OR REPLACE PROCEDURE VALIDERHEURES (P_IDENSEIGN IN ENSEIGNANT.IDENSEIGN%TYPE, P_NBH IN NUMBER)
IS
BEGIN
    IF P_NBH IS NULL OR P_NBH<0 
    THEN
        RAISE_APPLICATION_ERROR(-20111, 'Le nombre d''heure doit etre positif!');
    END IF;
    UPDATE ENSEIGNANT
    SET ENSEIGNANT.NBHDISP = P_NBH
    WHERE ENSEIGNANT.IDENSEIGN = P_IDENSEIGN;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20112, 'Enseignant introuvable');
    END IF;
END;
/